### ISSUE TITLE
Use max/min PHP constants instead of hard coded values

### ISSUE THREAD

**Issue by khalyomede** [chfoo/trandom#1]
## Description

In the source code, when targeting PHP, the `random_int()` function is called with hard coded min/max values when targeting Haxe 4.

https://github.com/chfoo/trandom/blob/5da39c5165ad1ed0cce5632650fa6e4941a17b4d/src/trandom/Native.hx#L55

## Expected behavior

In Haxe 4, the [`php.Const.PHP_INT_MIN`](https://api.haxe.org/php/Const.html#PHP_INT_MIN) and [`php.Const.PHP_INT_MAX`](https://api.haxe.org/php/Const.html#PHP_INT_MAX) are used instead.

**Comment by chfoo** [comment]
I am not sure of the advantages of using those PHP constants. `TargetRandom.random()` is defined to only return a 32-bit integer, so on a 64-bit PHP, returning anything larger is not well-defined and not portable across Haxe targets. It is something I wanted to avoid, especially if it is used in cryptographic situations to avoid mistakes. Is there something specific to your situation where using the PHP constants is important?

**Comment by khalyomede** [comment]
No importance for me, I was just looking at the code and was wondering.

Looks like these constants do not result in the integer values actually being hard coded, so it should stay safe to use them since it will be on the PHP interpreter to use 32/64 bits mode depending with which architecture the executable has been compiled with.

```haxe
#if php
import php.Const;
#end

class Main {
  public static function main() {
    final min = Const.PHP_INT_MIN;
    final max = Const.PHP_INT_MAX;
  }
}
```

```php
<?php

class Main {
  public static function main () {
    $min = PHP_INT_MIN;
    $max = PHP_INT_MAX;
  }
}
```
